Ht lesson02 skeleton
js-tasks-ru/htmlcss-20220414_eclips pull request #7
Opened 2022-04-30 13:06 UTC by GMBV

2022-04-30 13:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-30 17:11 UTC, GSemikozov requested changes

2022-04-30 17:11 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header-row:first-child {
этот класс можно оставить чисто для задания отступов. Но вообще skeleton__header-row + skeleton__body-row - это один и тот же элемент, например skeleton__row, но с разной шириной, которой можно управлять через модификаторы - skeleton__row_short и тд

2022-04-30 17:11 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 50%;
и высота кстати будет 20px

2022-05-08 05:08 UTC, GMBV commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header-row:first-child {
Объединил классы skeleton__header-row & skeleton__body-row, добавил миксы

2022-05-08 05:08 UTC, GMBV commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 50%;
поставил фиксированную высоту в 20px

2022-05-10 20:22 UTC, GSemikozov approved these changes, later dismissed

2022-05-10 20:22 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-05-10 20:22 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header-row:first-child {
остается исправить конфликт

2022-05-12 19:20 UTC, GSemikozov approved these changes

2022-05-12 19:20 UTC, merged